default: <%= ENV['MESSAGE_PUSHER_ENGINE'] || 'socky' %>

engines:
 pusher:
  app_id: <%= ENV['MESSAGE_PUSHER_PUSHER_APP_ID'] %>
  key:    <%= ENV['MESSAGE_PUSHER_PUSHER_KEY'] %>
  secret: <%= ENV['MESSAGE_PUSHER_PUSHER_SECRET'] %>
 keima:
  url: <%= ENV['MESSAGE_PUSHER_KEIMA_URL'] || 'http://localhost:3001' %>
  key: <%= ENV['MESSAGE_PUSHER_KEIMA_KEY'] || '4e7c45a1a2cb660517000001' %>
 socky:
  http: <%= ENV['MESSAGE_PUSHER_SOCKY_HTTP_URL'] || 'http://localhost:3002/http' %>
  web_socket: <%= ENV['MESSAGE_PUSHER_SOCKY_WS_URL'] || 'ws://localhost:3002/websocket' %>
  app: as
  secret: secret
