development:
  clients:
    default:
      hosts:
        - <%= ENV['MONGODB_HOST'] || 'localhost' %>:<%= ENV['MONGODB_PORT'] || 27017 %>
      database: asakusa_satellite_development

test:
  clients:
    default:
      hosts:
        - <%= ENV['MONGO_PORT_27017_TCP_ADDR'] || 'localhost' %>:27017
      database: asakusa_satellite_test

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGOHQ_URL'] || ENV['MONGOLAB_URI'] %>
